### ISSUE TITLE
ValidationError while syndicating. ckan.logic.ValidationError: None - {'extras': [{'key': ['There is a schema field with the same name']}, {}], '__type': 'Validation Error'}

### ISSUE THREAD

**Issue by vj-addnode** [aptivate/ckanext-syndicate#12]
**when I am setting syndicate value to true in custom fields of dataset it is giving me the below error at the time of sync. Am I missing any configuration in ckan?**

Traceback (most recent call last):
  File "C:\app\src\vckan\lib\site-packages\rq\worker.py", line 1068, in perform_job
    rv = job.perform()
  File "C:\app\src\vckan\lib\site-packages\rq\job.py", line 847, in perform
    self._result = self._execute()
  File "C:\app\src\vckan\lib\site-packages\rq\job.py", line 870, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "C:\app\src\ckanext-syndicate\ckanext\syndicate\tasks.py", line 56, in sync_package
    _update(package, profile)
  File "C:\app\src\ckanext-syndicate\ckanext\syndicate\tasks.py", line 153, in _update
    return _create(package, profile)
  File "C:\app\src\ckanext-syndicate\ckanext\syndicate\tasks.py", line 138, in _create
    remote_package = ckan.action.package_create(**new_package_data)
  File "C:\app\src\vckan\lib\site-packages\ckanapi\common.py", line 51, in action
    return self._ckan.call_action(name, data_dict=kwargs)
  File "C:\app\src\vckan\lib\site-packages\ckanapi\remoteckan.py", line 97, in call_action
    return reverse_apicontroller_action(url, status, response)
  File "C:\app\src\vckan\lib\site-packages\ckanapi\common.py", line 127, in reverse_apicontroller_action
    raise ValidationError(err)
ckan.logic.ValidationError: None - {'extras': [{'key': ['There is a schema field with the same name']}, {}], '__type': 'Validation Error'}

**Below is like how I am setting up the metadata for syndication**

![image](https://github.com/aptivate/ckanext-syndicate/assets/154971917/4f5d1873-2147-4a93-9b06-1865e46f5dd3)

**Comment by martinburchell** [comment]
@vj-addnode which versions of CKAN and ckanext-syndicate are you using? I was involved in the initial development. @smotornyuk has since updated the extension for later versions and I understand it has changed quite a bit.

**Comment by vj-addnode** [comment]
I am currently CKAN 2.10.1 and Syndicate V2. Also, does both the Ckan instance need syndicate to be installed ?

**Comment by martinburchell** [comment]
> I am currently CKAN 2.10.1 and Syndicate V2. Also, does both the Ckan instance need syndicate to be installed ?

Probably best to see if Sergey responds then. Certainly with the original version only the source CKAN instance needed the extension installed

**Comment by vj-addnode** [comment]
Sorry, the error was due to an internal plugin used. Closing the ticket.

**Comment by smotornyuk** [comment]
I'm sorry for not getting back to you sooner. Even though the problem is solved, I'd like to provide extra insight in case somebody else faces the same problem.

The issue with extra fields is not specific to the version of syndicate extension, and, is not related to it at all. It can be reproduced on a clean CKAN instance via API request to package_create(for example, using [ckanapi](https://github.com/ckan/ckanapi))
```sh
ckanapi action package_create name=anything extras:'[{"key":"notes","value":"hello"}]'
```

You have to provide an `extras` field and ensure that one of the extra keys matches any field defined in the package schema. I used the `notes` field in the example above. If you are extending schema with an extension like ckanext-scheming, you can also refer to any custom field registered via this extension.

Error means that you are trying to save an extra field that conflicts with an existing field registered in the normal package schema. Usually, it happens when you syndicate datasets between portals that use different metadata schemas. To fix the issue, check [extending section](https://github.com/aptivate/ckanext-syndicate?tab=readme-ov-file#extending) from readme. You need to implement ISyndicate.prepare_package_for_syndication:

```python
	plugins.implements(ISyndicate, inherit=True)

	def prepare_package_for_syndication(
		self, package_id: str, data_dict: dict[str, Any], profile: Profile
	) -> dict[str, Any]:
		data_dict.pop("extras", None)
		return data_dict
```

In this example I just removed all the extras to avoid conflict. But when you know exact schemas, it will be better to pick only specific extras, leaving all other records in place.

**Comment by vj-addnode** [comment]
I have scenario for this. I have some custom fields that I have added in dataset. Now, I want to syndicate these custom extra fields also but I am not able to, because it says the error "There is a schema field with the same name". Is there any solution?

**Comment by smotornyuk** [comment]
Yes, you must move custom fields outside of the extras collection inside `prepare_package_for_syndication`. 

Let's say you have custom field `cf`. You are trying to syndicate the dataset from the **source** portal to the **destination** portal. On the **destination** portal you have `cf` defined in the dataset metadata schema.

Right now, **source** sends something like this to the **destination**: 
`{"name": "dataset-name", "extras": [{"key": "cf", "value": "***"}]}`

`cf` field is transferred inside `extras`, while **destination** expects it to be available on the top-level of the dictionary, i.e: `{"name": "dataset-name", "cf": "***"}`

In the end you'll have the implementation of ISyndicate similar to the following:
```python
FIELDS_THAT_SHOULD_NOT_BE_SYNDICATED = ...

class MyPlugin(...):
	plugins.implements(ISyndicate, inherit=True)

	def prepare_package_for_syndication(
		self, package_id: str, data_dict: dict[str, Any], profile: Profile
	) -> dict[str, Any]:
		extras = data_dict.pop("extras", [])
                for field in extras:
                    if field["key"] in FIELDS_THAT_SHOULD_NOT_BE_SYNDICATED:
                        continue
                    data_dict[field["key"]] = field["value"]
		return data_dict
```

**Comment by vj-addnode** [comment]
Yes. I found this solution only after writing the comment. Only thing is, I am doing this in Tasks.py file. Thanks.
